package com.voltwise.ui.screens

@Suppress("UNUSED_PARAMETER")
fun appText(languageCode: String, text: String): String {
    return canonicalText(text)
}

private fun canonicalText(text: String): String {
    translations.values.forEach { language ->
        language.entries.firstOrNull { it.value == text }?.let { return it.key }
    }
    return text
}

@Suppress("UNUSED_PARAMETER")
fun screenTitle(languageCode: String, route: String?, fallback: String): String = appText(
    "en",
    when (route) {
        "command_center" -> "Overview"
        "lab" -> "Lab"
        "timeline" -> "Activity"
        "forecast" -> "Forecast"
        "history" -> "History"
        "insights" -> "Insights"
        "doctor" -> "Doctor"
        "missions" -> "Missions"
        "settings" -> "Settings"
        else -> fallback
    }
)

private val translations: Map<String, Map<String, String>> = mapOf(
    "hi" to mapOf(
        "Overview" to "ओवरव्यू",
        "Lab" to "लैब",
        "Activity" to "गतिविधि",
        "Forecast" to "पूर्वानुमान",
        "History" to "इतिहास",
        "Insights" to "इनसाइट्स",
        "Settings" to "सेटिंग्स",
        "Analytics" to "विश्लेषण",
        "Doctor" to "डॉक्टर",
        "Missions" to "मिशन",
        "Make it yours" to "इसे अपना बनाएं",
        "Your preferences. Your battery data." to "आपकी पसंद. आपका बैटरी डेटा.",
        "Display" to "डिस्प्ले",
        "Power saving & system state" to "पावर सेविंग और सिस्टम स्थिति",
        "Monitoring & privacy" to "मॉनिटरिंग और गोपनीयता",
        "Alerts" to "अलर्ट",
        "System battery settings" to "सिस्टम बैटरी सेटिंग्स",
        "Play Store & Legal" to "प्ले स्टोर और कानूनी",
        "On your device" to "आपके डिवाइस पर",
        "The story of your battery" to "आपकी बैटरी की कहानी",
        "Every connection. Every charging milestone." to "हर कनेक्शन. हर चार्जिंग पड़ाव.",
        "Battery percentage over time" to "समय के साथ बैटरी प्रतिशत",
        "Collecting battery activity" to "बैटरी गतिविधि एकत्र हो रही है",
        "Keep monitoring active to build a simple percentage vs time graph." to "सरल प्रतिशत बनाम समय ग्राफ के लिए मॉनिटरिंग चालू रखें.",
        "Less than 1 min tracked" to "1 मिनट से कम ट्रैक हुआ",
        "Easy charging graph: higher line means more battery. Touch or drag to inspect any time." to "सरल चार्जिंग ग्राफ: ऊंची लाइन मतलब ज्यादा बैटरी. किसी भी समय देखने के लिए छुएं या खींचें.",
        "battery" to "बैटरी",
        "LAST 24 HOURS" to "पिछले 24 घंटे",
        "Start" to "शुरुआत",
        "Now" to "अब",
        "Change" to "बदलाव",
        "Explore & understand" to "जानें और समझें",
        "Battery Lab" to "बैटरी लैब",
        "Get to know the way you charge." to "आप कैसे चार्ज करते हैं, इसे समझें.",
        "Current" to "करंट",
        "Temperature" to "तापमान",
        "Charge time and health" to "चार्ज समय और स्वास्थ्य",
        "Time to full" to "पूरा होने का समय",
        "Health score" to "स्वास्थ्य स्कोर",
        "Battery details" to "बैटरी विवरण",
        "Health" to "स्वास्थ्य",
        "Technology" to "तकनीक",
        "This charging session" to "यह चार्जिंग सत्र",
        "Current not supported on this device" to "इस डिवाइस पर करंट समर्थित नहीं है",
        "Wattage not supported on this device" to "इस डिवाइस पर वॉटेज समर्थित नहीं है",
        "Connect a charger to start your next session." to "अगला सत्र शुरू करने के लिए चार्जर कनेक्ट करें.",
        "min" to "मिनट",
        "Connected" to "कनेक्टेड",
        "Battery gained" to "बैटरी बढ़ी",
        "Connected at 100%" to "100% पर कनेक्टेड",
        "Power reflects the battery, not the charger's rated output." to "पावर बैटरी को दिखाता है, चार्जर की रेटेड आउटपुट को नहीं.",
        "Hide sensor diagnostics" to "सेंसर डायग्नोस्टिक्स छिपाएं",
        "Sensor diagnostics" to "सेंसर डायग्नोस्टिक्स",
        "Raw sensor values" to "कच्चे सेंसर मान",
        "Converted current" to "बदला हुआ करंट",
        "Current units: mA · RMX2151 firmware correction" to "करंट यूनिट: mA · RMX2151 फर्मवेयर सुधार",
        "Current units: µA ÷ 1000" to "करंट यूनिट: µA ÷ 1000",
        "Status / source" to "स्थिति / स्रोत",
        "Raw temperature" to "कच्चा तापमान",
        "Battery level" to "बैटरी स्तर",
        "Updated" to "अपडेट हुआ",
        "Current" to "करंट",
        "Power" to "पावर",
        "Temp" to "तापमान",
        "Wattage" to "वॉटेज",
        "Compact" to "कॉम्पैक्ट",
        "Easy live graphs" to "सरल लाइव ग्राफ",
        "Simple lines: higher means more of that reading. The dot at the end is your latest value." to "सरल लाइन: ऊंची लाइन का मतलब उस रीडिंग का ज्यादा मान. अंत का डॉट नवीनतम मान है.",
        "Charging strength" to "चार्जिंग ताकत",
        "Current shows charging speed. Voltage shows battery pressure." to "करंट चार्जिंग स्पीड दिखाता है. वोल्टेज बैटरी दबाव दिखाता है.",
        "Power going into battery" to "बैटरी में जा रही पावर",
        "More watts usually means faster charging." to "ज्यादा वॉट का मतलब आमतौर पर तेज चार्जिंग.",
        "Battery temperature" to "बैटरी तापमान",
        "Lower and steady is better for battery health." to "कम और स्थिर तापमान बैटरी के लिए बेहतर है.",
        "Voltage" to "वोल्टेज",
        "High" to "ज्यादा",
        "Low" to "कम",
        "now" to "अब",
        "Learning" to "सीख रहा है",
        "Collecting more readings to draw this clearly." to "ग्राफ साफ दिखाने के लिए और रीडिंग जुटाई जा रही हैं.",
        "readings in this view" to "रीडिंग इस दृश्य में",
        "Getting started" to "शुरुआत करें",
        "Use your phone normally for a few hours." to "कुछ घंटों तक फोन सामान्य रूप से इस्तेमाल करें.",
        "Voltwise learns from plugged and unplugged samples. Activity, Insights and Forecast become more useful as history builds." to "Voltwise प्लग और अनप्लग नमूनों से सीखता है. इतिहास बनने पर Activity, Insights और Forecast ज्यादा उपयोगी होते हैं.",
        "Tip: connect a charger and leave monitoring active for at least 10 minutes to unlock better charger speed estimates." to "टिप: बेहतर चार्जर स्पीड अनुमान के लिए चार्जर कनेक्ट करें और मॉनिटरिंग कम से कम 10 मिनट चालू रखें.",
        "Good" to "अच्छा",
        "Unknown" to "अज्ञात",
        "Charging" to "चार्ज हो रहा है",
        "Discharging" to "डिस्चार्ज हो रहा है",
        "Full" to "पूरा",
        "Not charging" to "चार्ज नहीं हो रहा"
    ),
    "es" to mapOf(
        "Overview" to "Resumen",
        "Lab" to "Laboratorio",
        "Activity" to "Actividad",
        "Forecast" to "Pronóstico",
        "History" to "Historial",
        "Insights" to "Datos",
        "Settings" to "Ajustes",
        "Analytics" to "Analítica",
        "Doctor" to "Doctor",
        "Missions" to "Misiones",
        "Make it yours" to "Hazlo tuyo",
        "Your preferences. Your battery data." to "Tus preferencias. Tus datos de batería.",
        "Display" to "Pantalla",
        "Power saving & system state" to "Ahorro de energía y sistema",
        "Monitoring & privacy" to "Monitoreo y privacidad",
        "Alerts" to "Alertas",
        "System battery settings" to "Ajustes de batería del sistema",
        "Play Store & Legal" to "Play Store y legal",
        "On your device" to "En tu dispositivo",
        "The story of your battery" to "La historia de tu batería",
        "Every connection. Every charging milestone." to "Cada conexión. Cada hito de carga.",
        "Battery percentage over time" to "Porcentaje de batería en el tiempo",
        "Collecting battery activity" to "Recopilando actividad de batería",
        "Keep monitoring active to build a simple percentage vs time graph." to "Mantén el monitoreo activo para crear un gráfico simple.",
        "Less than 1 min tracked" to "Menos de 1 min registrado",
        "Easy charging graph: higher line means more battery. Touch or drag to inspect any time." to "Gráfico simple: una línea más alta significa más batería. Toca o arrastra para ver cualquier momento.",
        "battery" to "batería",
        "LAST 24 HOURS" to "ÚLTIMAS 24 HORAS",
        "Start" to "Inicio",
        "Now" to "Ahora",
        "Change" to "Cambio",
        "Explore & understand" to "Explora y entiende",
        "Battery Lab" to "Laboratorio de batería",
        "Get to know the way you charge." to "Conoce cómo cargas.",
        "Current" to "Corriente",
        "Temperature" to "Temperatura",
        "Charge time and health" to "Tiempo de carga y salud",
        "Time to full" to "Tiempo para llenar",
        "Health score" to "Salud",
        "Battery details" to "Detalles de batería",
        "Health" to "Salud",
        "Technology" to "Tecnología"
    ),
    "fr" to mapOf(
        "Overview" to "Aperçu",
        "Lab" to "Labo",
        "Activity" to "Activité",
        "Forecast" to "Prévision",
        "History" to "Historique",
        "Insights" to "Infos",
        "Settings" to "Réglages",
        "Analytics" to "Analyse",
        "Doctor" to "Docteur",
        "Missions" to "Missions",
        "Make it yours" to "Personnalisez",
        "Your preferences. Your battery data." to "Vos préférences. Vos données batterie.",
        "Display" to "Affichage",
        "Power saving & system state" to "Économie d'énergie et système",
        "Monitoring & privacy" to "Suivi et confidentialité",
        "Alerts" to "Alertes",
        "System battery settings" to "Réglages batterie système",
        "Play Store & Legal" to "Play Store et légal",
        "On your device" to "Sur votre appareil",
        "The story of your battery" to "L'histoire de votre batterie",
        "Every connection. Every charging milestone." to "Chaque connexion. Chaque étape de charge.",
        "Battery percentage over time" to "Pourcentage de batterie dans le temps",
        "Collecting battery activity" to "Collecte de l'activité batterie",
        "Keep monitoring active to build a simple percentage vs time graph." to "Gardez le suivi actif pour créer un graphique simple.",
        "Less than 1 min tracked" to "Moins de 1 min suivie",
        "Easy charging graph: higher line means more battery. Touch or drag to inspect any time." to "Graphique simple : plus la ligne est haute, plus il y a de batterie. Touchez ou glissez pour inspecter.",
        "battery" to "batterie",
        "LAST 24 HOURS" to "DERNIÈRES 24 H",
        "Start" to "Début",
        "Now" to "Maintenant",
        "Change" to "Changement",
        "Explore & understand" to "Explorer et comprendre",
        "Battery Lab" to "Labo batterie",
        "Get to know the way you charge." to "Comprenez votre façon de charger.",
        "Current" to "Courant",
        "Temperature" to "Température",
        "Charge time and health" to "Temps de charge et santé",
        "Time to full" to "Temps avant plein",
        "Health score" to "Score santé",
        "Battery details" to "Détails batterie",
        "Health" to "Santé",
        "Technology" to "Technologie"
    ),
    "de" to mapOf(
        "Overview" to "Übersicht",
        "Lab" to "Labor",
        "Activity" to "Aktivität",
        "Forecast" to "Prognose",
        "History" to "Verlauf",
        "Insights" to "Einblicke",
        "Settings" to "Einstellungen",
        "Analytics" to "Analyse",
        "Doctor" to "Doktor",
        "Missions" to "Missionen",
        "Make it yours" to "Mach es zu deinem",
        "Your preferences. Your battery data." to "Deine Einstellungen. Deine Akkudaten.",
        "Display" to "Anzeige",
        "Power saving & system state" to "Energiesparen und System",
        "Monitoring & privacy" to "Überwachung und Datenschutz",
        "Alerts" to "Warnungen",
        "System battery settings" to "System-Akkueinstellungen",
        "Play Store & Legal" to "Play Store und Rechtliches",
        "On your device" to "Auf deinem Gerät",
        "The story of your battery" to "Die Geschichte deines Akkus",
        "Every connection. Every charging milestone." to "Jede Verbindung. Jeder Lade-Meilenstein.",
        "Battery percentage over time" to "Akkustand im Zeitverlauf",
        "Collecting battery activity" to "Akkuaktivität wird gesammelt",
        "Keep monitoring active to build a simple percentage vs time graph." to "Lass die Überwachung aktiv, um einen einfachen Graphen zu erstellen.",
        "Less than 1 min tracked" to "Weniger als 1 Min. erfasst",
        "Easy charging graph: higher line means more battery. Touch or drag to inspect any time." to "Einfacher Ladegraph: höhere Linie bedeutet mehr Akku. Tippen oder ziehen zum Prüfen.",
        "battery" to "Akku",
        "LAST 24 HOURS" to "LETZTE 24 STUNDEN",
        "Start" to "Start",
        "Now" to "Jetzt",
        "Change" to "Änderung",
        "Explore & understand" to "Erkunden und verstehen",
        "Battery Lab" to "Akkulabor",
        "Get to know the way you charge." to "Verstehe, wie du lädst.",
        "Current" to "Strom",
        "Temperature" to "Temperatur",
        "Charge time and health" to "Ladezeit und Zustand",
        "Time to full" to "Zeit bis voll",
        "Health score" to "Zustand",
        "Battery details" to "Akkudetails",
        "Health" to "Zustand",
        "Technology" to "Technologie"
    ),
    "ar" to mapOf(
        "Overview" to "نظرة عامة",
        "Lab" to "المختبر",
        "Activity" to "النشاط",
        "Forecast" to "التوقع",
        "History" to "السجل",
        "Insights" to "الرؤى",
        "Settings" to "الإعدادات",
        "Analytics" to "التحليل",
        "Doctor" to "الطبيب",
        "Missions" to "المهام",
        "Make it yours" to "اجعله مناسبا لك",
        "Your preferences. Your battery data." to "تفضيلاتك. بيانات بطاريتك.",
        "Display" to "العرض",
        "Power saving & system state" to "توفير الطاقة وحالة النظام",
        "Monitoring & privacy" to "المراقبة والخصوصية",
        "Alerts" to "التنبيهات",
        "System battery settings" to "إعدادات بطارية النظام",
        "Play Store & Legal" to "المتجر والقانون",
        "On your device" to "على جهازك",
        "The story of your battery" to "قصة بطاريتك",
        "Every connection. Every charging milestone." to "كل اتصال. كل مرحلة شحن.",
        "Battery percentage over time" to "نسبة البطارية مع الوقت",
        "Collecting battery activity" to "يتم جمع نشاط البطارية",
        "Keep monitoring active to build a simple percentage vs time graph." to "أبق المراقبة نشطة لبناء رسم بسيط.",
        "Less than 1 min tracked" to "أقل من دقيقة متتبعة",
        "Easy charging graph: higher line means more battery. Touch or drag to inspect any time." to "رسم بسيط: الخط الأعلى يعني بطارية أكثر. المس أو اسحب للفحص.",
        "battery" to "بطارية",
        "LAST 24 HOURS" to "آخر 24 ساعة",
        "Start" to "البداية",
        "Now" to "الآن",
        "Change" to "التغيير",
        "Explore & understand" to "استكشف وافهم",
        "Battery Lab" to "مختبر البطارية",
        "Get to know the way you charge." to "تعرف على طريقة شحنك.",
        "Current" to "التيار",
        "Temperature" to "الحرارة",
        "Charge time and health" to "وقت الشحن والصحة",
        "Time to full" to "الوقت للاكتمال",
        "Health score" to "الصحة",
        "Battery details" to "تفاصيل البطارية",
        "Health" to "الصحة",
        "Technology" to "التقنية"
    )
)
